services:
  postgres:
    image: postgres:17
    container_name: saborfy-db

    environment:
      POSTGRES_DB: saborfy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    build: .
    container_name: "saborfy_api"

    depends_on:
      - postgres

    ports:
      - "8081:8081"

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/saborfy
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  postgres_data: