CREATE TABLE "order"
(
    number        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    observation   VARCHAR(255),
    status        VARCHAR(255) NOT NULL,
    delivery      BOOLEAN  DEFAULT FALSE NOT NULL,
    tab_id        BIGINT NOT NULL,
    restaurant_id BIGINT NOT NULL,
    created_by    BIGINT NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    canceled_at   TIMESTAMP WITHOUT TIME ZONE,
    canceled_by   BIGINT,
    cancel_reason VARCHAR(255),
    CONSTRAINT pk_order PRIMARY KEY (number),
    CONSTRAINT fk_order_tab
        FOREIGN KEY (tab_id)
        REFERENCES tab(id),

    CONSTRAINT fk_order_restaurant
        FOREIGN KEY (restaurant_id)
        REFERENCES restaurant(id),

    CONSTRAINT fk_order_user_creation
        FOREIGN KEY (created_by)
        REFERENCES users(id),

    CONSTRAINT fk_order_user_cancel
        FOREIGN KEY (canceled_by)
        REFERENCES users(id)
);