CREATE TABLE order_item
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id     BIGINT                                  NOT NULL,
    product_id   BIGINT,
    product_name VARCHAR(50),
    unit_price   DECIMAL                                 NOT NULL,
    quantity     INTEGER                                 NOT NULL,
    observation  VARCHAR(255),
    CONSTRAINT pk_orderitem PRIMARY KEY (id)
);

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDERITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES "order" (number);