CREATE TABLE section
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome          VARCHAR(50)                             NOT NULL,
    active        BOOLEAN DEFAULT TRUE                    NOT NULL,
    restaurant_id BIGINT                                  NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_section PRIMARY KEY (id),
    CONSTRAINT fk_section_user
        FOREIGN KEY (restaurant_id)
        REFERENCES restaurant(id)
);