CREATE TABLE payment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tab_id         BIGINT NOT NULL ,
    value          DECIMAL NOT NULL ,
    payment_method VARCHAR(255) NOT NULL,
    observation    VARCHAR(255),
    restaurant_id BIGINT NOT NULL ,
    registered_by  BIGINT NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payment PRIMARY KEY (id),

    CONSTRAINT fk_payment_tab
        FOREIGN KEY (tab_id)
        REFERENCES tab(id),

    CONSTRAINT fk_payment_users
        FOREIGN KEY (registered_by)
        REFERENCES users(id),

    CONSTRAINT fk_payment_restaurant
        FOREIGN KEY (restaurant_id)
        REFERENCES restaurant(id)
);