CREATE TABLE refresh_token (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL,
        token_hash VARCHAR(64) NOT NULL UNIQUE,
        revoked BOOLEAN NOT NULL DEFAULT FALSE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

        CONSTRAINT fk_refresh_tokens_user
            FOREIGN KEY (user_id)
            REFERENCES users(id)
);

CREATE INDEX idx_refresh_tokens_user_id
    ON refresh_token(user_id);