CREATE TABLE tab
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    status        VARCHAR(255) NOT NULL,
    section_id    BIGINT NOT NULL,
    restaurant_id BIGINT NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_tab PRIMARY KEY (id),

    CONSTRAINT fk_tab_restaurant
        FOREIGN KEY (restaurant_id)
        REFERENCES restaurant(id),

    CONSTRAINT fk_tab_section
        FOREIGN KEY (section_id)
        REFERENCES section(id)
);