CREATE TABLE category
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(50),
    active        BOOLEAN DEFAULT TRUE NOT NULL,
    restaurant_id BIGINT,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_category
        PRIMARY KEY (id),

    CONSTRAINT fk_category_restaurant
        FOREIGN KEY (restaurant_id)
        REFERENCES restaurant(id)
);