CREATE TABLE product
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(150),
    description   VARCHAR(255),
    price         DECIMAL,
    available     BOOLEAN                                 NOT NULL,
    active        BOOLEAN                                 NOT NULL,
    category_id   BIGINT,
    restaurant_id BIGINT,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_product PRIMARY KEY (id),

    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id)
        REFERENCES category(id),

    CONSTRAINT fk_product_restaurant
        FOREIGN KEY (restaurant_id)
        REFERENCES restaurant(id)

);